const saboresLista = [
    {nome:"Alho e Óleo", ing:"Molho, mussarela, alho, Catupiry e parmesão"},
    {nome:"Atum", ing:"Molho, mussarela, atum ralado e tomates picados"},
    {nome:"Bacon", ing:"Molho, mussarela e bacon picado"},
    {nome:"Bacon ao 4 Queijos", ing:"Molho, mussarela, provolone, parmesão, Catupiry e bacon picado"},
    {nome:"Bacon com Cheddar", ing:"Molho, mussarela, bacon picado e cheddar"},
    {nome:"Brócolis", ing:"Molho, mussarela, brócolis e Catupiry"},
    {nome:"Brócolis com Bacon", ing:"Molho, mussarela, brócolis e bacon picado"},
    {nome:"Calabresa", ing:"Molho, mussarela e calabresa fatiada em rodelas"},
    {nome:"Calabresa Acebolada", ing:"Molho, mussarela, calabresa, cebola e azeitona"},
    {nome:"Camarão", ing:"Molho, mussarela, camarão ao molho vermelho e orégano (Adicional R$9,00)"},
    {nome:"Carne de Panela com Doritos", ing:"Molho, mussarela, carne de panela desfiada e Doritos"},
    {nome:"Carbonara", ing:"Molho, mussarela, bacon, cebola, ovos picados e creme de leite"},
    {nome:"Cinco Queijos", ing:"Molho, mussarela, Catupiry, provolone, parmesão e gorgonzola"},
    {nome:"Chester", ing:"Molho, mussarela, chester, Catupiry e orégano"},
    {nome:"Coração", ing:"Molho, mussarela, coração de galinha ao molho vermelho"},
    {nome:"Copa com Figo", ing:"Molho, mussarela, copa fatiada e figo em calda"},
    {nome:"Corn Bacon", ing:"Molho, mussarela, bacon picado e milho"},
    {nome:"Filé", ing:"Molho, mussarela, iscas de carne ao molho e Catupiry"},
    {nome:"Filé ao Alho e Óleo", ing:"Molho, mussarela, iscas de carne e alho"},
    {nome:"Filé aos 4 Queijos", ing:"Molho, mussarela, provolone, parmesão, Catupiry e iscas de carne"},
    {nome:"Filé ao molho Mostarda", ing:"Molho, mussarela, iscas de carne e molho de mostarda"},
    {nome:"Filé com Palha", ing:"Molho, mussarela, iscas de carne e batata palha"},
    {nome:"Frango com Catupiry", ing:"Molho, mussarela, frango desfiado e Catupiry"},
    {nome:"Frango com Cheddar", ing:"Molho, mussarela, frango desfiado e cheddar"},
    {nome:"Frango com Milho", ing:"Molho, mussarela, frango desfiado e milho"},
    {nome:"Fricassê de Carne", ing:"Molho, mussarela, iscas de carne, creme de leite e batata palha"},
    {nome:"Fricassê de Frango", ing:"Molho, mussarela, frango em cubos, creme de leite e batata palha"},
    {nome:"Italiana", ing:"Molho, mussarela, salame, azeitona, cebola e orégano"},
    {nome:"Jardineira", ing:"Molho, mussarela, milho, ervilha, palmito, pimentão e cebola"},
    {nome:"Lasanha", ing:"Molho, mussarela, carne moída e Catupiry"},
    {nome:"Lombo", ing:"Molho, mussarela, lombo canadense e Catupiry"},
    {nome:"Lombo com Abacaxi", ing:"Molho, mussarela, lombo canadense e abacaxi picado"},
    {nome:"Marguerita", ing:"Molho, mussarela, tomate em rodelas, manjericão e Catupiry"},
    {nome:"Mexicana", ing:"Molho, mussarela, carne moída, cebola, pimentão e pimenta"},
    {nome:"Milho", ing:"Molho, mussarela, milho e orégano"},
    {nome:"Milho ao Molho Branco", ing:"Molho, mussarela, milho e creme de leite"},
    {nome:"Mussarela", ing:"Molho, mussarela e orégano"},
    {nome:"Palmito", ing:"Molho, mussarela, palmito e tomate picado"},
    {nome:"Picanha", ing:"Molho, mussarela e fatias de picanha (Adicional R$9,00)"},
    {nome:"Picanha ao Alho e Óleo", ing:"Molho, mussarela, fatias de picanha e alho"},
    {nome:"Portuguesa", ing:"Molho, mussarela, presunto, ovos, azeitona e cebola"},
    {nome:"Quatro Queijos", ing:"Molho, mussarela, Catupiry, provolone e parmesão"},
    {nome:"Romana", ing:"Molho, mussarela, presunto, tomate em rodelas e parmesão"},
    {nome:"Seis Queijos", ing:"Molho, mussarela, Catupiry, provolone, parmesão e cheddar"},
    {nome:"Siciliana", ing:"Molho, mussarela, bacon, champignon, azeitonas e Catupiry"},
    {nome:"Strogonoff de Carne", ing:"Molho, mussarela, iscas de carne ao molho de strogonoff"},
    {nome:"Strogonoff de Frango", ing:"Molho, mussarela, frango em cubos ao molho vermelho e Catupiry"},
    {nome:"Tomate Seco com Rúcula", ing:"Molho, mussarela, tomate seco e rúcula"},
    {nome:"Tropical", ing:"Molho, mussarela, calabresa moída, palmito e Catupiry"},
    {nome:"Vegetariana", ing:"Molho, mussarela, palmito, milho, ervilha, brócolis, parmesão e orégano"},
    {nome:"Abacaxi", ing:"Doce de leite, abacaxi picado e chocolate branco"},
    {nome:"Abacaxi com Coco", ing:"Doce de leite, chocolate branco, coco ralado e calda de chocolate"},
    {nome:"Amendoim", ing:"Doce de leite, amendoim e chocolate preto ou branco"},
    {nome:"Banana", ing:"Doce de leite, banana, canela e chocolate branco"},
    {nome:"Beijinho", ing:"Chocolate branco, coco ralado e leite condensado"},
    {nome:"Branca de Neve", ing:"Doce de leite e chocolate branco"},
    {nome:"Califórnia", ing:"Doce de leite, pêssego, figo, abacaxi, canela, mussarela e leite condensado"},
    {nome:"Chocolate Branco com Nozes", ing:"Doce de leite, chocolate branco e nozes picada (Adicional R$5,00)"},
    {nome:"Dois Amores", ing:"Doce de leite, chocolate branco e chocolate preto"},
    {nome:"M&M's", ing:"Doce de leite, chocolate branco ou preto e MM's"},
    {nome:"Morango Branco", ing:"Doce de leite, chocolate branco, morangos picados e creme de leite"},
    {nome:"Morango Moreno", ing:"Doce de leite, chocolate preto, morangos picado e creme de leite"},
    {nome:"Nega Maluca", ing:"Doce de leite e chocolate preto"},
    {nome:"Prestígio", ing:"Doce de leite, chocolate preto e coco ralado"},
    {nome:"Romeo e Julieta", ing:"Leite condensado, goiabada, creme de leite e muçarela"},
    {nome:"Sonho de Valsa", ing:"Doce de leite, chocolate preto e Sonho de Valsa picado"},
    {nome:"Oreo", ing:"Doce de leite, chocolate preto e Oreo (Adicional R$5,00)"},
    {nome:"Ouro Branco", ing:"Doce de leite, chocolate branco e Ouro branco picado"}
]